# Generated by Django 2.2.7 on 2021-03-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210327_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pic',
            new_name='picture',
        ),
    ]
